.PHONY: all

all:
	gcc -O2 -shared -o test_module.so -fPIC test_module.c msgpuck/msgpuck.c msgpuck/hints.c -I ~/Sources/work/tarantool-ee/tarantool/third_party/luajit/src -I ~/Sources/work/tarantool-ee/build_rwdi/tarantool/src
